// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQ6oW39ZYPAsD-_zv3JFmzN6NyI15l7w',
    appId: '1:458723311102:web:e3edfa46e82064627094af',
    messagingSenderId: '458723311102',
    projectId: 'efootball-76fcf',
    authDomain: 'efootball-76fcf.firebaseapp.com',
    storageBucket: 'efootball-76fcf.firebasestorage.app',
    measurementId: 'G-XGZPDPFDBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbjVaUnBwCFEwnhGLXvywdvypPX47lckY',
    appId: '1:458723311102:android:2b5cfeaafc17589b7094af',
    messagingSenderId: '458723311102',
    projectId: 'efootball-76fcf',
    storageBucket: 'efootball-76fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPSNtOqwdU-kvhyklwB2H6Eq88zfaMmlI',
    appId: '1:458723311102:ios:5ca1fd69e6998e2f7094af',
    messagingSenderId: '458723311102',
    projectId: 'efootball-76fcf',
    storageBucket: 'efootball-76fcf.firebasestorage.app',
    iosBundleId: 'com.efootball.efootballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPSNtOqwdU-kvhyklwB2H6Eq88zfaMmlI',
    appId: '1:458723311102:ios:5ca1fd69e6998e2f7094af',
    messagingSenderId: '458723311102',
    projectId: 'efootball-76fcf',
    storageBucket: 'efootball-76fcf.firebasestorage.app',
    iosBundleId: 'com.efootball.efootballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfQ6oW39ZYPAsD-_zv3JFmzN6NyI15l7w',
    appId: '1:458723311102:web:675531c4916129d87094af',
    messagingSenderId: '458723311102',
    projectId: 'efootball-76fcf',
    authDomain: 'efootball-76fcf.firebaseapp.com',
    storageBucket: 'efootball-76fcf.firebasestorage.app',
    measurementId: 'G-MK0VLK3SZX',
  );
}
