import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import '../theme/app_theme.dart';
import '../models/tournament_model.dart';
import '../models/team_model.dart';
import '../data/firebase_service.dart';

class CreateTournamentScreen extends StatefulWidget {
  const CreateTournamentScreen({super.key});

  @override
  State<CreateTournamentScreen> createState() => _CreateTournamentScreenState();
}

class _CreateTournamentScreenState extends State<CreateTournamentScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _regionController = TextEditingController(text: 'Global');
  TournamentType _selectedType = TournamentType.epl;
  
  final List<TeamDraft> _teams = [
    TeamDraft(name: '', manager: '', logoAsset: 'arsenal.png'),
    TeamDraft(name: '', manager: '', logoAsset: 'mancity.png'),
  ];

  final List<String> _availableLogos = [
    'arsenal.png', 'astonvilla.png', 'bournemouth.png', 'brentford.png',
    'brighton.png', 'burnley.png', 'chelsea.png', 'crystalpalace.png',
    'everton.png', 'fulham.png', 'ipswich.png', 'leeds.png',
    'leicester.png', 'liverpool.png', 'mancity.png', 'manutd.png',
    'newcastle.png', 'nottmforest.png', 'sheffieldutd.png', 'southampton.png',
    'sunderland.png', 'tottenham.png', 'westbrom.png', 'westham.png', 'wolves.png'
  ];

  void _addTeam() {
    setState(() {
      _teams.add(TeamDraft(name: '', manager: '', logoAsset: 'arsenal.png'));
    });
  }

  void _removeTeam(int index) {
    if (_teams.length > 2) {
      setState(() {
        _teams.removeAt(index);
      });
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("A tournament must have at least 2 teams.")),
      );
    }
  }

  Future<void> _saveTournament() async {
    if (!_formKey.currentState!.validate()) return;

    final firebaseService = context.read<FirebaseService>();
    
    // Create tournament object
    final tournament = Tournament(
      id: '', // Will be generated by Firestore
      name: _nameController.text,
      region: _regionController.text,
      type: _selectedType,
      createdAt: DateTime.now(),
    );

    // Create team objects
    final teams = _teams.map((t) => Team(
      id: '', // Will be generated
      name: t.name,
      shortName: t.name.length >= 3 ? t.name.substring(0, 3).toUpperCase() : t.name.toUpperCase(),
      logoUrl: 'assets/logos/${t.logoAsset}',
      managerId: 'user',
      managerName: t.manager,
    )).toList();

    try {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => const Center(child: CircularProgressIndicator(color: AppTheme.accentGreen)),
      );

      // We need to implement this method in FirebaseService
      await firebaseService.createNewTournament(tournament, teams);

      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Tournament created successfully!")),
        );
        context.pop(); // Go back
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: $e")),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.cardColorLight,
      appBar: AppBar(
        title: const Text("Create Tournament", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: AppTheme.primaryPurple,
        foregroundColor: Colors.white,
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            _buildSectionTitle("Tournament Details"),
            const SizedBox(height: 12),
            _buildTextField(_nameController, "Tournament Name", Icons.emoji_events),
            const SizedBox(height: 12),
            _buildTextField(_regionController, "Region/League Name", Icons.public),
            const SizedBox(height: 16),
            
            const Text("Tournament Logic", style: TextStyle(fontWeight: FontWeight.bold, color: AppTheme.primaryPurple)),
            const SizedBox(height: 8),
            _buildLogicDropdown(),
            
            const SizedBox(height: 32),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _buildSectionTitle("Teams & Players"),
                TextButton.icon(
                  onPressed: _addTeam,
                  icon: const Icon(Icons.add, color: AppTheme.primaryPurple),
                  label: const Text("Add Team", style: TextStyle(color: AppTheme.primaryPurple, fontWeight: FontWeight.bold)),
                ),
              ],
            ),
            const SizedBox(height: 8),
            ..._teams.asMap().entries.map((entry) => _buildTeamCard(entry.key, entry.value)),
            
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: _saveTournament,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primaryPurple,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              child: const Text("CREATE TOURNAMENT", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: AppTheme.primaryPurple),
    );
  }

  Widget _buildTextField(TextEditingController controller, String label, IconData icon) {
    return TextFormField(
      controller: controller,
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon, color: AppTheme.primaryPurple),
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: AppTheme.primaryPurple, width: 2)),
      ),
      validator: (value) => value == null || value.isEmpty ? "Required" : null,
    );
  }

  Widget _buildLogicDropdown() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButtonFormField<TournamentType>(
          value: _selectedType,
          decoration: const InputDecoration(border: InputBorder.none),
          items: const [
            DropdownMenuItem(value: TournamentType.epl, child: Text("Premier League Logic (Classic Table)")),
            DropdownMenuItem(value: TournamentType.uefa, child: Text("UEFA Logic (Groups + Knockout)")),
          ],
          onChanged: (val) {
            if (val != null) setState(() => _selectedType = val);
          },
        ),
      ),
    );
  }

  Widget _buildTeamCard(int index, TeamDraft team) {
    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      elevation: 0,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Row(
              children: [
                CircleAvatar(
                  backgroundColor: AppTheme.cardColorLight,
                  radius: 25,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Image.asset('assets/logos/${team.logoAsset}'),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    children: [
                      TextFormField(
                        initialValue: team.name,
                        decoration: const InputDecoration(hintText: "Team Name", isDense: true, border: InputBorder.none),
                        onChanged: (val) => team.name = val,
                        validator: (value) => value == null || value.isEmpty ? "Required" : null,
                      ),
                      const Divider(height: 1),
                      TextFormField(
                        initialValue: team.manager,
                        decoration: const InputDecoration(hintText: "Manager/Player Name", isDense: true, border: InputBorder.none),
                        onChanged: (val) => team.manager = val,
                        validator: (value) => value == null || value.isEmpty ? "Required" : null,
                      ),
                    ],
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.image_search, color: AppTheme.primaryPurple),
                  onPressed: () => _pickLogo(index),
                ),
                IconButton(
                  icon: const Icon(Icons.delete_outline, color: Colors.red),
                  onPressed: () => _removeTeam(index),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  void _pickLogo(int index) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) {
        return Container(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text("Select Team Logo", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppTheme.primaryPurple)),
              const SizedBox(height: 16),
              SizedBox(
                height: 300,
                child: GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 5, mainAxisSpacing: 10, crossAxisSpacing: 10),
                  itemCount: _availableLogos.length,
                  itemBuilder: (context, i) {
                    final logo = _availableLogos[i];
                    return InkWell(
                      onTap: () {
                        setState(() {
                          _teams[index].logoAsset = logo;
                        });
                        Navigator.pop(context);
                      },
                      child: Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          border: Border.all(color: _teams[index].logoAsset == logo ? AppTheme.primaryPurple : Colors.transparent, width: 2),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Image.asset('assets/logos/$logo'),
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}

class TeamDraft {
  String name;
  String manager;
  String logoAsset;

  TeamDraft({required this.name, required this.manager, required this.logoAsset});
}
