import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../theme/app_theme.dart';
import '../data/firebase_service.dart';
import '../models/tournament_model.dart';
import '../models/team_model.dart';

class JoinTournamentScreen extends StatefulWidget {
  const JoinTournamentScreen({super.key});

  @override
  State<JoinTournamentScreen> createState() => _JoinTournamentScreenState();
}

class _JoinTournamentScreenState extends State<JoinTournamentScreen> {
  final _formKey = GlobalKey<FormState>();
  final _teamNameController = TextEditingController();
  final _managerNameController = TextEditingController();
  
  String? _selectedTournamentId;
  String? _selectedLogo;
  List<String> _usedLogos = [];
  bool _isLoadingUsedLogos = false;

  final List<String> _availableLogos = [
    'arsenal.png', 'astonvilla.png', 'bournemouth.png', 'brentford.png',
    'brighton.png', 'burnley.png', 'chelsea.png', 'crystalpalace.png',
    'everton.png', 'fulham.png', 'ipswich.png', 'leeds.png',
    'leicester.png', 'liverpool.png', 'mancity.png', 'manutd.png',
    'newcastle.png', 'nottmforest.png', 'sheffieldutd.png', 'southampton.png',
    'sunderland.png', 'tottenham.png', 'westbrom.png', 'westham.png', 'wolves.png'
  ];

  void _onTournamentChanged(String? tournamentId) async {
    if (tournamentId == null) return;
    
    setState(() {
      _selectedTournamentId = tournamentId;
      _isLoadingUsedLogos = true;
      _selectedLogo = null; // Reset logo when tournament changes
    });

    final firebaseService = context.read<FirebaseService>();
    final usedLogos = await firebaseService.getUsedLogos(tournamentId);

    setState(() {
      _usedLogos = usedLogos;
      _isLoadingUsedLogos = false;
    });
  }

  Future<void> _joinTournament() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedTournamentId == null || _selectedLogo == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Please select a tournament and a logo.")),
      );
      return;
    }

    final firebaseService = context.read<FirebaseService>();
    
    final team = Team(
      id: '', // Generated by Firestore
      name: _teamNameController.text,
      shortName: _teamNameController.text.length >= 3 
          ? _teamNameController.text.substring(0, 3).toUpperCase() 
          : _teamNameController.text.toUpperCase(),
      logoUrl: 'assets/logos/$_selectedLogo',
      managerId: 'user', // Assuming authenticated user or generic 'user'
      managerName: _managerNameController.text,
    );

    try {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => const Center(child: CircularProgressIndicator(color: AppTheme.accentGreen)),
      );

      await firebaseService.joinTournament(_selectedTournamentId!, team);

      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Joined tournament successfully!")),
        );
        context.go('/home'); // Go back to home/navigation
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error: $e")),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.cardColorLight,
      appBar: AppBar(
        title: const Text("Join Tournament", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: AppTheme.primaryPurple,
        foregroundColor: Colors.white,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            if (Navigator.canPop(context)) {
              Navigator.of(context).pop();
            } else {
              context.go('/home');
            }
          },
        ),
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            const Text(
              "Join an Existing Tournament",
              style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppTheme.primaryPurple),
            ),
            const SizedBox(height: 8),
            Text(
              "Select a tournament and set up your team profile.",
              style: TextStyle(color: Colors.grey.shade600),
            ),
            const SizedBox(height: 32),

            // Tournament Selection
            _buildDropdownSection(),
            const SizedBox(height: 24),

            // Team Details
            if (_selectedTournamentId != null) ...[
              _buildTextField(_teamNameController, "Team Name", Icons.shield_outlined),
              const SizedBox(height: 16),
              _buildTextField(_managerNameController, "Manager Name", Icons.person_outline),
              const SizedBox(height: 24),

              // Logo Selection
              const Text(
                "Select Team Logo",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppTheme.primaryPurple),
              ),
              const SizedBox(height: 12),
              _buildLogoGrid(),
              
              const SizedBox(height: 40),
              ElevatedButton(
                onPressed: _joinTournament,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primaryPurple,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 18),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  elevation: 4,
                ),
                child: const Text("JOIN TOURNAMENT", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
              ),
            ],
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildDropdownSection() {
    final firebaseService = context.read<FirebaseService>();
    
    return StreamBuilder<List<Tournament>>(
      stream: firebaseService.getTournaments(),
      builder: (context, snapshot) {
        final tournaments = snapshot.data ?? [];
        
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 10)],
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButtonFormField<String>(
              initialValue: _selectedTournamentId,
              hint: const Text("Select Tournament"),
              decoration: const InputDecoration(border: InputBorder.none),
              items: tournaments.map((t) => DropdownMenuItem(
                value: t.id,
                child: Text(t.name),
              )).toList(),
              onChanged: _onTournamentChanged,
              validator: (value) => value == null ? "Required" : null,
            ),
          ),
        );
      },
    );
  }

  Widget _buildTextField(TextEditingController controller, String label, IconData icon) {
    return TextFormField(
      controller: controller,
      decoration: InputDecoration(
        labelText: label,
        prefixIcon: Icon(icon, color: AppTheme.primaryPurple),
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: AppTheme.primaryPurple, width: 2)),
      ),
      validator: (value) => value == null || value.isEmpty ? "Required" : null,
    );
  }

  Widget _buildLogoGrid() {
    if (_isLoadingUsedLogos) {
      return const Center(child: Padding(
        padding: EdgeInsets.all(20.0),
        child: CircularProgressIndicator(color: AppTheme.primaryPurple),
      ));
    }

    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.withValues(alpha: 0.1)),
      ),
      padding: const EdgeInsets.all(12),
      child: GridView.builder(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 5,
          mainAxisSpacing: 10,
          crossAxisSpacing: 10,
        ),
        itemCount: _availableLogos.length,
        itemBuilder: (context, index) {
          final logo = _availableLogos[index];
          final fullLogoPath = 'assets/logos/$logo';
          final isUsed = _usedLogos.contains(fullLogoPath);
          final isSelected = _selectedLogo == logo;

          return InkWell(
            onTap: isUsed ? null : () {
              setState(() {
                _selectedLogo = logo;
              });
            },
            child: Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: isSelected ? AppTheme.primaryPurple.withValues(alpha: 0.1) : (isUsed ? Colors.grey.withValues(alpha: 0.1) : Colors.transparent),
                border: Border.all(
                  color: isSelected ? AppTheme.primaryPurple : (isUsed ? Colors.transparent : Colors.grey.withValues(alpha: 0.2)),
                  width: 2,
                ),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Opacity(
                opacity: isUsed ? 0.3 : 1.0,
                child: Image.asset(
                  'assets/logos/$logo',
                  errorBuilder: (context, error, stackTrace) => const Icon(Icons.broken_image, size: 20),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
